vich_uploader:
    db_driver: orm

    mappings:
        document_fichier:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer:
                service: "vich_uploader.namer_uniqid"
        logo_fichier:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            delete_on_update: true
            namer:
                service: "vich_uploader.namer_uniqid"
        photo_fichier:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer:
                service: "vich_uploader.namer_uniqid"