vich_uploader:
    db_driver: orm

    mappings:
        document_fichier:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer:
                service: "vich_uploader.namer_uniqid"