#index:
#    path: /
#    controller: App\Controller\DefaultController::index

entreprise_login_check:
    path: /entreprise/login_check

client_login_check:
    path: /client/login_check

logout_entreprise:
    path: /entreprise/logout

logout_client:
    path: /client/logout